spring:
  rabbitmq:
    password: root
    username: root
    port: 5672
    addresses: aliyun.yanyan.site
    #开启发送失败返回
    publisher-returns: true
    #支持消息的确认与返回
    template:
      mandatory: true
