spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-rxranzeo.cd.tencentcdb.com:10084/ts?serverName=mysql-server&queryInterceptors=site.yan.mysql.interceptor.TSQueryInterceptor&exceptionInterceptors=site.yan.mysql.interceptor.TSExceptionInterceptor&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Ca66771111

server:
  port: 8080

ts:
  enable: true
  autoReport: true
  autoReportUrl: http://114.116.251.70:56/report
  server-name: Java-application
  stage: beta
  traceIgnoreUrls:
    - /favicon.ico
