spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.116.251.70:3306/ts?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Ca66771111

server:
  port: 90

ts:
  enable: true
  server-name: Java-application
  stage: beta