spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.yanyan.site:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Ca66771111

server:
  port: 90

ts:
  enable: true
  server-name: haha
  stage: beta